import type { IRSite } from "../ir/types.js";

export function renderReadme(site: IRSite): string {
  const routes = site.pages.map((p) => `- \`${p.path}\` → \`src/routes/${p.path === "/" ? "index" : p.path.replace(/^\//, "")}.tsx\``).join("\n");
  return `# ${site.name}

Generated from a Framer design by **framecoded** into a clean, editable
[TanStack Start](https://tanstack.com/start) project — plain React + CSS Modules, yours to edit.

## Getting started

\`\`\`bash
npm install
npm run dev      # http://localhost:3000
\`\`\`

## Domain and SEO

The export contains a \`.env\` with a domain placeholder. Replace it with the public deployment domain:

\`\`\`bash
VITE_SITE_URL=https://example.com
\`\`\`

This value is required. There is intentionally no fallback domain.

The same value drives canonical links, Open Graph URLs, JSON-LD, \`robots.txt\`, and
\`sitemap.xml\`. The two public SEO files are regenerated automatically before
\`npm run dev\` and \`npm run build\`.

## Build & self-host

\`\`\`bash
npm run build    # client + SSR build into .output/
npm run start    # node .output/server/index.mjs  ->  http://localhost:3000
\`\`\`

The official Nitro Node adapter serves the generated client assets and TanStack Start SSR
handler from \`.output/\`. Deploy it anywhere Node runs (a VPS, a container, Fly, Render,
Railway). Set \`PORT\`/\`HOST\` to configure. To wire your **own backend**, add TanStack Start server functions
(\`createServerFn\`) or fetch \`import.meta.env.VITE_API_BASE_URL\` (see \`.env\`).

## Project structure

\`\`\`
src/
  routes/            # file-based routes (one per page) with SEO head() metadata
    __root.tsx       # <html> shell, global <head>, favicons
  components/         # page namespace, then one self-contained folder per component
    <Page>/index.ts   # page-level component exports
    <Page>/<Component>/
      index.ts        # public component export
      <Component>.tsx
      <Component>.module.css
  styles/
    global.css       # imported Framer resets, fonts, keyframes
    theme.css        # color styles as CSS variables — edit to recolor everything
  ui/Image.tsx       # optimized <img>: lazy + async decode, eager/high-priority LCP
public/
  assets/             # local responsive images, fonts, CSS images, and media
  favicon*           # favicons fetched from the Framer project
  robots.txt
  sitemap.xml
\`\`\`

## Routes

${routes}

## What was preserved / generated

- Layout, colors, typography, and structure converted to plain CSS Modules.
- Framer motion replayed with the browser's native Web Animations API: exact captured
  keyframes, spring samples, delays, infinite tickers, and viewport-triggered reveals.
- Interactive CSS states and transitions retained without a Framer runtime dependency.
- Desktop, tablet, and phone renders folded into one editable DOM with CSS media-query
  overrides, including breakpoint-specific interaction geometry.
- SEO: per-page \`<title>\`, meta description, Open Graph + Twitter cards, canonical
  links, JSON-LD structured data, \`sitemap.xml\`, \`robots.txt\`.
- Favicons fetched and wired into the document head.
- Images: local responsive \`srcset\`, lazy loading, async decoding, intrinsic dimensions to
  avoid layout shift; the first image per page is prioritized for LCP.
- Missing image \`alt\` text generated automatically.

---
Generated by [framecoded](https://github.com/) · source: ${site.source.origin}
`;
}
